#!/bin/bash

SCRIPT_DIR=$(dirname $(readlink -f "$0"))

dn=$(dirname -- "$1")
fp=$(readlink -f $1)
fn=$(basename -- "$fp")
filename="${fn%.*}"

outname=$SCRIPT_DIR/out/$dn/$filename

if [ -f "$outname" ]; then
    $outname
else
    ./build $fp
    $outname
fi