#!/bin/bash

SCRIPT_DIR=$(dirname $(readlink -f "$0"))

dn=$(dirname -- "$1")
fp=$(readlink -f $1)
fn=$(basename -- "$fp")
filename="${fn%.*}"

# Check for the correct number of arguments
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <command> <n>"
    exit 1
fi

# Initialize an empty list
output_list=()

# The command to run and the number of times to run it
command="./run $dn/$filename"
n="$2"

# Run the command 'n' times and append the last line of output to the list
for ((i = 1; i <= n; i++)); do
    output=$(eval "$command" 2>/dev/null)
    last_line=$(echo -e "$output" | tail -n 1)
    output_list+=("$last_line")
done

# Display the resulting list
echo "Resulting list:"
for item in "${output_list[@]}"; do
    echo "$item"
done
